excluded:
  - .build
  - Sources/ArchivistComponents/VLCUI

identifier_name:
  excluded:
    - db
    - vc
    - id

type_name:
  allowed_symbols: []
  excluded:
    - iPadChannelsScreen
    - iPhoneChannelsScreen
    - iPadPlaylistsScreen
    - iPhonePlaylistsScreen
    - iPadSettingsScreen
    - iPhoneSettingsScreen
    - iPadTabScreen
    - iPadVideoListScreen
    - iPhoneVideoListScreen
    - iPadVideoDetailScreen
    - iPhoneVideoDetailScreen

type_body_length:
  warning: 800
  error: 1000

nesting:
  type_level: 2

file_length:
  warning: 900
  error: 1200

function_body_length:
  warning: 70
  error: 100

cyclomatic_complexity:
  warning: 17
  error: 25

function_parameter_count:
  warning: 9
  error: 12
